kind: Runtime.Definition
metadata:
  name: JobDefinition
  resourceKind: Job
  module: Pipeline
controllers:
  - runtime: 'node@>=20 <23'
    entrypoint: './nodejs/job.ts'
  - runtime: 'bun@>=1.1'
    entrypoint: './nodejs/job.ts'
schema:
  type: object
  properties:
    steps:
      type: array
      items:
        type: object
        properties:
          kind:
            type: string
            description: Resource kind (e.g., Logic.JavaScript, HttpClient.Request)
        required:
          - kind
  required:
    - steps
