kind: Runtime.Definition
metadata:
  name: JobDefinition
  resourceKind: Job
  module: Pipeline
controllers:
  - pkg:npm/@telorun/pipeline@>=1.0.0?local_path=./nodejs#job
schema:
  type: object
  properties:
    steps:
      type: array
      items:
        type: object
        properties:
          kind:
            type: string
            description: Resource kind (e.g., Logic.JavaScript, HttpClient.Request)
        required:
          - kind
  required:
    - steps
