kind: Runtime.Definition
metadata:
  name: SchemaDefinition
  resourceKind: Schema
  module: Assert
controllers:
  - pkg:npm/@telorun/assert@1.0.0?local_path=./nodejs#schema
  - runtime: nodejs
    registry: npm
    package: "@telorun/assert@1.0.0"
    entry: "./schema"
  - runtime: nodejs
    registry: local
    package: "./nodejs"
    entry: "./schema"
schema:
  type: object
  properties:
    metadata:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    schema:
      description: Value to assert (can be any type or expression)
  required:
    - metadata
    - assertions
