export type RuntimeErrorCode =
  | 'ERR_RESOURCE_NOT_FOUND'
  | 'ERR_CONTROLLER_NOT_FOUND'
  | 'ERR_CONTROLLER_INVALID'
  | 'ERR_RESOURCE_NOT_INVOKABLE'
  | 'ERR_DUPLICATE_RESOURCE'
  | 'ERR_EXECUTION_FAILED'
  | 'ERR_INVALID_VALUE'
  | 'ERR_VISIBILITY_DENIED';
